server:
  # default profile port
  port: 8080
  # UTF-8 사용
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.moment.the: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
  charset:
    console: UTF-8
  file:
    name: ./logs/product.log
    path: ./logs/product.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
      max-file-size: 500MB
      max-history: 1

spring:
  # H2 DataBase
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # DB 설정
  datasource:
    url: jdbc:h2:mem:the_moment
    driver-class-name: org.h2.Driver
    username: sa

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true

  # Message 설정
  messages:
    basename: i18n/exception
    encoding: UTF-8

  # Redis
  redis:
    image: redis:latest
    host: localhost
    port: 6379

  # JWT
  jwt:
    secret: asdkfhksldjhfkajsdhfasd7df67sa8d6f87as6df86sa8d7f6a8ds6f87a9s6d8f76sad87f687ad6f8asd76f8asd6f8asd6f87sd6f87asd6f87s